# Generated by Django 5.0.6 on 2024-06-27 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tujuan', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('supervisor', models.CharField(max_length=100)),
                ('anggota', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('Berlangsung', 'Berlangsung'), ('Selesai', 'Selesai'), ('Gagal', 'Gagal')], max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
