# Generated by Django 5.0.6 on 2024-06-28 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('implementasi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='activity',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='upload_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
