# Generated by Django 5.0.6 on 2024-06-28 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('implementasi', '0003_rename_end_date_project_project_management_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='activity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
