# Generated by Django 5.0.6 on 2024-07-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('implementasi', '0004_project_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='accuracy',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
