# Generated by Django 5.0.6 on 2024-07-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('implementasi', '0005_project_accuracy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='upload_file',
            new_name='uploaded_files',
        ),
        migrations.AddField(
            model_name='project',
            name='captured_photos',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
