# Generated by Django 5.0.6 on 2024-07-02 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('implementasi', '0006_rename_upload_file_project_uploaded_files_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='captured_photos',
        ),
        migrations.RemoveField(
            model_name='project',
            name='uploaded_files',
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='implementasi.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='implementasi.project')),
            ],
        ),
    ]
